.TH PHYSLOCK 1 physlock\-VERSION
.SH NAME
physlock \- lock all consoles / virtual terminals
.SH SYNOPSIS
.B physlock
.RB [ \-dhLlv ]
.RB [ \-u
.IR USER ]
.SH DESCRIPTION
physlock is an alternative to vlock, it is equivalent to `vlock \-an'. It is
written because vlock blocks some linux kernel mechanisms like hibernate and
suspend and can therefore only be used with some limitations.
.P
physlock is designed to be lightweight, but highly depends on the kernels ioctl
API.
.P
The behaviour of physlock is completely controlled via command-line arguments,
it does not rely on environment variables.
It always allows unlocking as root and as a specified user. If no username is
given on the command line, then physlock uses the name of the calling user.
.SH OPTIONS
.TP
.B \-d
Fork and detach physlock before prompting for authentication. The parent
process returns right after everything is set up, so this option is useful for
use in suspend/hibernate scripts.
.TP
.B \-h
Print brief usage information to standard output and exit.
.TP
.B \-l
Only lock console switching and exit.
.TP
.B \-L
Only enable (unlock) console switching and exit. This is useful when a prior
instance of physlock has crashed and leaved the console switching mechanism
locked.
.TP
.B \-v
Print version information to standard output and exit.
.TP
.B \-u USER
Allow the given user to unlock the computer. Using this option
disables physlocks mechanism to guess the currently active user by looking at
the file ownership of the foreground console device.
.SH AUTHORS
.TP
Bert Muennich <ber.t at gmx.com>
.SH HOMEPAGE
.TP
http://github.com/muennich/physlock
.SH SEE ALSO
.BR vlock (1)
